### PR TITLE
fix: disable node-fetch compress when checking integrity

### LINKED ISSUE #41: Fetching package from server which sends Content-type application/gzip fails integrity check
**Problem**: 
Fetching from a server, that serves the package with Content-type 'application/x-tgz' header, causes node-fetch to unpack the content before the integrity check is done and thus integrity check fails.

**Solution**:
When fetching with integrity check, we need to disable node-fetch compress, so that no decompression is made before the check.

**Background**
We are using [Nexus ](https://www.sonatype.com/nexus-repository-sonatype) with proxy setup (to npm registry) and Nexus allways checks the content and sets the appropriate content-type header. There is no way to disable this in Nexus, so now all packages that have checksum defined, fail...

**To reproduce**
Fetch a package with defined checksum from server, that sets "correct" Content-Type 'application/x-tgz' for a compressed packaged.

### PR DESCRIPTION
**Pull request by miiihi**
Fixes #41

### CODE REVIEW

**Review by zkat — APPROVED** [review]
Thanks for submitting this! I'm gonna take this cause it definitely addresses a specific pain point for npm users in the short-term.

At the same time, I feel like the full solution to this needs to be more involved: make-fetch-happen should still be able to verify integrity while decompressing requests. This is bound to be a footgun for users (which they can't work around), until... something gets figured out.

**Comment by miiihi** [comment]
Thanks for a quick merge. @zkat Can I ask, what's your release strategy with make-fetch-happen? That is, when can I expect this to be published... It'll really fix a big pain that we have :)

**Comment by miiihi** [comment]
Hi @zkat, can I repeat the question - what's your release strategy with make-fetch-happen? That is, when can I expect new version to be published... The bug that this pr fixed is really a big pain that we have :)

Thanks!

**Comment by zkat** [comment]
@miiihi This is already merged into `release-next` on npm, but it's pending a release while I fix some issue that happened with `pacote` that's blocking it. I'd expect to see a release by next week, if not this week.

**Pull request merged**
